http://localhost:3000

###
http://localhost:3000/categories

###
http://localhost:3000/categories/books

###
http://localhost:3000/categories/books/count

###
http://localhost:3000/categories/books/prices

###
http://localhost:3000/categories/672e3538a2a5c1a72454d839

###
http://localhost:3000/categories/672e3538a2a5c1a72454d839/books

###
http://localhost:3000/categories/672e3538a2a5c1a72454d839/books/prices